# This workflow will install Python dependencies and run tests on expected user platforms
name: Testing on user machines

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    #
    runs-on: ${{ matrix.platform }}
    #
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4
      #
    - name: Set up Python ${{ matrix.python-version }}
      #
      uses: actions/setup-python@v5
      with:
        #
        python-version: ${{ matrix.python-version }}
        #
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[test]
    - name: Run tests
      run: pytest --pyargs padre_sharp --cov padre_sharp
      env:
        #
        PLATFORM: ${{ matrix.platform }}
        #
